version: '2'
services:
    nhtsa-api:
        image: webdevops/php-apache-dev:alpine-php7
        container_name: nhtsa-api
        restart: always
        env_file: .env
        ports:
         - "${DOCKER_EXPOSE_PORT}:80"
        volumes:
         - ./:/app
        working_dir: /app
        tty: true


