version: '2'
services:
    php:
        image: webdevops/php-apache:alpine-php7
        container_name: php
        restart: always
        env_file: .env
        ports:
         - "${DOCKER_EXPOSE_PORT}:80"
        volumes:
         - ./:/app
        working_dir: /app
        tty: true


